name: Contract Tests - Scheduled

on:
  schedule:
    - cron: "*/0 1 * * 1-5"  # Executar uma vez por dia útil às 1 da manhã


jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar o ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      
      - name: Instalar gems
        run: bundler install
        
      - name: Instalar o cucumber
        run: gem install bundler cucumber
        
      - name: Executar contract tests
        run: rake contract

      - name: Slack notification - Success
        uses: rtCamp/action-slack-notify@v2

        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ruby-test-report
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.clipartmax.com/png/middle/179-1795386_patient-success-success-icon-png.png
          SLACK_MESSAGE: ':alarm_clock: Testes Agendados executados com Sucesso! :white_check_mark:'
          SLACK_TITLE: ':alarm_clock: Testes Agendados executados com Sucesso! :white_check_mark:'
          SLACK_USERNAME: SUCESSO
        
      - name: Slack notification - Falha
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ruby-test-report
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.vhv.rs/dpng/d/431-4316378_error-icon-hope-for-justice-logo-hd-png.png
          SLACK_MESSAGE: ':alarm_clock: Testes Agendados executados com Falhas! :fire:'
          SLACK_TITLE: ':alarm_clock: Testes Agendados executados com Falhas! :fire:'
          SLACK_USERNAME: FALHA
          