name: Contract Tests - Scheduled

on:
  schedule:
    - cron: "*/5 1-23 * * *"    #"0 1 * * 1-5"  # Executar uma vez por dia útil às 1 da manhã


jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar o ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
      
      - name: Instalar gems
        run: bundler install
        
      - name: Instalar o cucumber
        run: gem install bundler cucumber
        
      - name: Executar contract tests
        run: rake contract
  
      - name: Remover relatório existente
        run: rm -f reports/features_report.html  

      - name: Slack notification - Success
        uses: rtCamp/action-slack-notify@v2

        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ruby-test-report
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.clipartmax.com/png/middle/160-1601781_a-little-cute-app-to-wake-you-up-near-your-destination-alarm.png
          SLACK_MESSAGE: ':alarm_clock: Testes Agendados executados com Sucesso! :white_check_mark:'
          SLACK_TITLE: ':alarm_clock: Testes Agendados executados com Sucesso! :white_check_mark:'
          SLACK_USERNAME: SUCESSO
        
      - name: Slack notification - Falha
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ruby-test-report
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.clipartmax.com/png/middle/362-3627812_failed-failed-failed-png.png
          SLACK_MESSAGE: ':alarm_clock: Testes Agendados executados com Falhas! :fire:'
          SLACK_TITLE: ':alarm_clock: Testes Agendados executados com Falhas! :fire:'
          SLACK_USERNAME: FALHA
          